m

diff --git a/init_files_variables_and_expansions/9-divide_and_rule b/init_files_variables_and_expansions/9-divide_and_rule
--- a/init_files_variables_and_expansions/9-divide_and_rule
+++ b/init_files_variables_and_expansions/9-divide_and_rule
@@ -1,2 +1,2 @@
 #!/bin/bash
-echo "$((POWER / DIVIDE))"
+[ -z "$POWER" ] || [ -z "$DIVIDE" ] || [ "$DIVIDE" -eq 0 ] && echo "Error: Invalid input" || echo $((POWER / DIVIDE))
